### ISSUE TITLE
Color scale - 

### ISSUE THREAD

**Issue by praftery** [CenterForTheBuiltEnvironment/mrt#1]
aka that thing Paul was harping on about

Add a feature to lock in the range for the temperature color scale. I think this should be the default actually, as it is seems more useful that way. e.g. min and max of 17 and 27°C, with the switch from blue to red happening in the middle at 22°C.

@thoyt

**Comment by stefanoschiavon** [comment]
For any visualization (PMV, mrt, etc) the scale should be lockable.

**Comment by thoyt** [comment]
486305ea660eeba1ee183511d923564d0b7ed292
