### ISSUE TITLE
raise temperature limit from 100

### ISSUE THREAD

**Issue by dheinzerling** [CenterForTheBuiltEnvironment/mrt#13]
Is there a mathematical reason to make the upper limit 100 for surface temperatures or is it just what seemed reasonable and easy to dial-in with a slider? We had a case where we wanted to look at electric resistance radiant panels--which are like 1000°F. I manually entered the value using the console, but I could see others wanting to try something higher than 100 as well.

**Comment by praftery** [comment]
Also just had a request to allow below 0 temps too, for cold climates.
