### ISSUE TITLE
Geometry doesn't render on chrome

### ISSUE THREAD

**Issue by praftery** [CenterForTheBuiltEnvironment/mrt#14]
Tool no longer renders geometry when I navigate to the test page on Chrome. Amazingly it does still work on Microsoft Edge browser!

![image](https://cloud.githubusercontent.com/assets/7246762/22523165/35979c48-e873-11e6-9817-0ff6a166d741.png)

**Comment by dheinzerling** [comment]
Still works for me in Chrome. Perhaps this was a weird Chrome version-specific issue
